[package]
name = "eldroid-ssg"
version = "0.1.0"
edition = "2024"

[dependencies]
serde = { version = "1.0.197", features = ["derive"] }
toml = "0.8.10"
rayon = "1.8.1"
log = "0.4.21"
env_logger = "0.11.2"
html5ever = "0.31.0"
markup5ever = "0.16.1"
markup5ever_rcdom = "0.2.0"
reqwest = { version = "0.12.15", features = ["blocking"] }
mime = "0.3.17"
image = { version = "0.25.0", features = ["jpeg", "png", "webp"], default-features = false }
regex = "1.10.3"
walkdir = "2.5.0"
once_cell = "1.19.0"
parking_lot = "0.12.1"
serde_json = "1.0.114"
chrono = { version = "0.4.35", features = ["serde"] }
sitemap = "0.4.1"
rss = "2.0.7"
