[package]
name = "eldroid-ssg"
version = "0.1.0"
edition = "2024"

[dependencies]
serde = { version = "1.0", features = ["derive"] }
toml = "0.8.21"
rayon = "1.5"
log = "0.4.27"
env_logger = "0.11.8"
html5ever = "0.26"
markup5ever_rcdom = "0.2"
reqwest = { version = "0.11", features = ["blocking"] }
mime = "0.3"
image = { version = "0.24", features = ["jpeg", "png", "webp"], default-features = false }
regex = "1.7"
walkdir = "2.5.0"
once_cell = "1.21.3"
parking_lot = "0.12.3"
serde_json = "1.0.140"
chrono = { version = "0.4", features = ["serde"] }
sitemap = "0.4"
rss = "2.0"
