[package]
name = "eldroid-ssg"
version = "0.1.0"
edition = "2024"

[dependencies]
serde = { version = "1.0", features = ["derive"] }
toml = "0.8.21"
rayon = "1.5"
log = "0.4.27"
env_logger = "0.11.8"
regex = "1.7"
walkdir = "2.5.0"
once_cell = "1.21.3"
parking_lot = "0.12.3"
