use std::fs;
use std::path::Path;
use std::io::Write;

pub fn generate_template_site(target_dir: &Path) -> std::io::Result<()> {
    // Create directories
    fs::create_dir_all(target_dir.join("content/blog"))?;
    fs::create_dir_all(target_dir.join("components"))?;
    fs::create_dir_all(target_dir.join("static/css"))?;
    fs::create_dir_all(target_dir.join("static/images"))?;

    // Sample Home Page
    fs::write(target_dir.join("content/index.html"), r#"---
title: Welcome to Eldroid SSG
description: A modern static site generator demo site.
tags: [home, welcome]
---
<MyHeader/>

# Welcome to Eldroid SSG

This is a sample homepage generated by the template generator. Explore the features below:

- Component system
- Markdown with diagrams
- SEO & social tags
- Blog support
- Dark/light theme

<MyFooter/>
"#)?;

    // Sample About Page
    fs::write(target_dir.join("content/about.html"), r#"---
title: About This Site
description: Learn about the Eldroid SSG demo site.
tags: [about]
---
<MyHeader/>

# About

This site was generated with the Eldroid SSG template generator. You can customize it freely!

<MyFooter/>
"#)?;

    // Sample Header Component
    fs::write(target_dir.join("components/Header.html"), r#"<header class='site-header'>
  <nav>
    <a href='/'>Home</a> |
    <a href='/about.html'>About</a> |
    <a href='/blog/first-post.html'>Blog</a>
  </nav>
</header>"#)?;

    // Sample Footer Component
    fs::write(target_dir.join("components/Footer.html"), r#"<footer class='site-footer'>
  <p>&copy; 2025 Eldroid SSG Demo. Powered by Rust.</p>
</footer>"#)?;

    // Sample Blog Post 1
    fs::write(target_dir.join("content/blog/first-post.md"), r#"---
title: First Blog Post
date: 2025-06-15
author: Demo User
description: This is your first blog post with Eldroid SSG!
tags: [blog, demo, getting-started]
keywords: [eldroid, ssg, blog]
image: /static/images/demo.png
---
<MyHeader/>

# First Blog Post

Welcome to your new blog! This post demonstrates:
- Markdown
- Components
- SEO frontmatter
- Diagrams

## Mermaid Example
```mermaid
graph TD
    A[Start] --> B{Try Mermaid}
    B -- Yes --> C[Success]
    B -- No --> D[Try Again]
```

<MyFooter/>
"#)?;

    // Sample Blog Post 2
    fs::write(target_dir.join("content/blog/second-post.md"), r#"---
title: Second Blog Post
date: 2025-06-15
author: Demo User
description: Another post to show more features.
tags: [blog, features]
keywords: [eldroid, ssg, features]
---
<MyHeader/>

# Second Blog Post

This post shows Graphviz and PlantUML diagrams:

## Graphviz Example
```graphviz
digraph G {
  A -> B;
  B -> C;
  C -> A;
}
```

## PlantUML Example
```plantuml
@startuml
Alice -> Bob: Hello
@enduml
```

<MyFooter/>
"#)?;

    // Sample CSS (optional, can be extended)
    fs::write(target_dir.join("static/css/custom.css"), r#".site-header { background: var(--md-code-bg); padding: 1em; }
.site-footer { background: var(--md-blockquote-bg); padding: 1em; text-align: center; }
"#)?;

    Ok(())
}
